#!/bin/sh
# Copyright 2023 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Delete temporary client files.

OKTA_TOKEN_FILE=/tmp/okta-token.json
STS_TOKEN_FILE="/tmp/sts-token.json"
SA_TOKEN_FILE="/tmp/service-account-token.json"
BUCKET_CONFIG_FILE=/tmp/bucket-config.json
CREATE_BUCKET_RESULTS_FILE=/tmp/create-bucket-results
DELETE_BUCKET_RESULTS_FILE=/tmp/delete-bucket-results

ARRAY_OF_FILES=( \
"$OKTA_TOKEN_FILE" \
"$STS_TOKEN_FILE" \
"$SA_TOKEN_FILE" \
"$BUCKET_CONFIG_FILE" \
"$CREATE_BUCKET_RESULTS_FILE" \
"$DELETE_BUCKET_RESULTS_FILE" \
)

echo Beginning deletion of temporary project files...

for FILE in ${ARRAY_OF_FILES[@]}
do
  echo deleting $FILE...
  rm -f $FILE
done

echo All temporary project files have been deleted.
