#!/bin/sh

# Create the service account to which access will be granted.

echo Creating service account $SERVICE_ACCOUNT_NAME...
gcloud iam service-accounts create "$SERVICE_ACCOUNT_BASE" \
--display-name="$SERVICE_ACCOUNT_BASE" \
--description="Service Account for Workload Identity lab"
echo Creation of service account completed.
