#!/bin/sh
# Copyright 2023 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Add the workloadIdentityUser permission to the service account

cat <<EOF
Adding service-account level bindings...

Adding iam.workloadIdentityUser for the following principal:
Principal workload pool: $WORKLOAD_POOL 
Principal workload provider: $WORKLOAD_PROVIDER
Service account: $SERVICE_ACCOUNT_BASE
Project number: $PROJECT_NUMBER

EOF

gcloud iam service-accounts add-iam-policy-binding $SERVICE_ACCOUNT_NAME \
--member="principal://iam.googleapis.com/projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/$WORKLOAD_POOL/subject/$SUBJECT" \
--role="roles/iam.workloadIdentityUser" \
--no-user-output-enabled

echo Addition of service-account level bindings completed.
