#!/bin/sh

# Add project level bindings for the service account

# The storage.admin role is needed for creating and deleting buckets.

echo Adding bindings for $SERVICE_ACCOUNT_BASE in project $PROJECT_ID...

echo Adding the storage.admin role...
gcloud projects add-iam-policy-binding $PROJECT_ID \
--member="serviceAccount:$SERVICE_ACCOUNT_NAME" \
--role="roles/storage.admin" \
--no-user-output-enabled

# The serviceUsageConsumer role is needed for Workload Identity Federation.

echo Adding the serviceusage.serviceUsageConsumer role...
gcloud projects add-iam-policy-binding $PROJECT_ID \
--member="serviceAccount:$SERVICE_ACCOUNT_NAME" \
--role="roles/serviceusage.serviceUsageConsumer" \
--no-user-output-enabled

echo Addition of project-level bindings completed.
