#!/bin/sh
# Copyright 2023 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Remove project level bindings for the service account

# The storage.admin role is needed for creating and deleting buckets.

echo Removing bindings for $SERVICE_ACCOUNT_BASE in project $PROJECT_ID...

echo Removing the storage.admin role...
gcloud projects remove-iam-policy-binding $PROJECT_ID \
--member="serviceAccount:$SERVICE_ACCOUNT_NAME" \
--role="roles/storage.admin" \
--no-user-output-enabled

# The serviceUsageConsumer role is needed for Workload Identity Federation.

echo Removing the serviceusage.serviceUsageConsumer role...
gcloud projects remove-iam-policy-binding $PROJECT_ID \
--member="serviceAccount:$SERVICE_ACCOUNT_NAME" \
--role="roles/serviceusage.serviceUsageConsumer" \
--no-user-output-enabled

echo Removal of project-level bindings completed.
echo Binding removal completed.
