#!/bin/sh

# Remove the workloadIdentityUser permission to the service account

cat <<EOF
Removing service-account level bindings...

Removing iam.workloadIdentityUser for the following principal:
Principal workload pool: $WORKLOAD_POOL 
Principal workload provider: $WORKLOAD_PROVIDER
Service account: $SERVICE_ACCOUNT_BASE
Project number: $PROJECT_NUMBER

EOF

gcloud iam service-accounts remove-iam-policy-binding $SERVICE_ACCOUNT_NAME \
--member="principal://iam.googleapis.com/projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/$WORKLOAD_POOL/subject/$SUBJECT" \
--role="roles/iam.workloadIdentityUser" \
--no-user-output-enabled

echo Removal of service-account level bindings completed.
