#!/bin/sh

# Delete the service account 

echo Deleting service account $SERVICE_ACCOUNT_NAME...
gcloud iam service-accounts delete "$SERVICE_ACCOUNT_NAME" \
  --quiet
echo Deletion of service account completed.
